name: dress
channels:
  - conda-forge
  - bioconda
dependencies:
    - python=3.10.12
    - pip=24.0
    - meme=5.5.5
    - pip:
       - tensorflow==2.15.0.post1
       - spliceai==1.3.1
       - GeneticEngine==0.8.5
       - torch==2.2.0 --index-url https://download.pytorch.org/whl/cu113
       - git+https://github.com/tkzeng/Pangolin.git@5cf94b8 
       - pandas==2.0.3
       - numpy==1.23.5
       - scikit-learn==1.4.0
       - pyranges==0.0.129
       - biopython==1.83
       - loguru
       - tqdm
       - rich_click
       - jsonschema
       - pyyaml
       - pandarallel

