---
# Mandatory arguments (input) should be provided as command line arguments to the script.
generate:
  dry_run: false
  verbosity: 0
  seed: 0
  shuffle_input: null
  model: 'spliceai'
  model_scoring_metric: 'mean'
  pangolin_mode: 'ss_usage'
  pangolin_tissue: null
  disable_gpu: null
  outdir: 'output'
  outbasename: null
  preprocessing:
    cache_dir: 'data/cache/' 
    genome: 'data/cache/Homo_sapiens.GRCh38.dna.primary_assembly.fa'
    use_full_sequence: false
  fitness:
    minimize_fitness: false
    fitness_function: 'bin_filler'
    fitness_threshold: 0.0
  archive:
    archive_size: 5000
    archive_diversity_metric: 'normalized_shannon'
    prune_archive_individuals: false
    prune_at_generations: null
  population:
    population_size: 1000
  selection:
    selection_method: 'tournament'
    tournament_size: 5
    custom_mutation_operator: false
    custom_mutation_operator_weight: 0.9
    mutation_probability: 0.9
    crossover_probability: 0.01 
    operators_weight:
      - 0.6
    elitism_weight:
      - 0.05
    novelty_weight:
      - 0.35
    update_weights_at_generation: null
  stopping:
    stopping_criterium: 
      - archive_size
      - time
    stop_at_value:
      - 5000
      - 5
    stop_when_all: false
  tracking_evolution:
    disable_tracking: false
    track_full_population: false
    track_full_archive: false
  grammar:
    which_grammar: 'random'
    max_diff_units: 6
    snv_weight: 0.33
    insertion_weight: 0.33
    deletion_weight: 0.33
    motif_substitution_weight: 0
    motif_ablation_weight: 0
    acceptor_untouched_range:
      - -10
      - 2
    donor_untouched_range:
      - -3
      - 6
    untouched_regions: null
    max_insertion_size: 5
    max_deletion_size: 5
    motif_db: 'ATtRACT'
    motif_search: 'fimo'
    subset_rbps: 'encode'
    min_nucleotide_probability: 0.15
    min_motif_length: 5
    qvalue_threshold: 0.01